version: "3.7"

services:
  questdb:
    image: questdb/questdb
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
  app:
    image: node:16.15-alpine3.14
    container_name: app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./:/app
  migration:
    image: node:16.15-alpine3.14
    command: sh -c "npm run migrate"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - questdb
      - app
