 version: "3.7"

 services:
  app:
    image: node:16.15-alpine3.14
    command: sh -c "npm install && npm run start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  questdb:
    image: questdb/questdb
    container_name: docker_questdb
    restart: always
    ports:
      - "8812:8812"
      - "9000:9000"
      - "9009:9009"
      - "9003:9003"
